FROM docker.guadaltel.es/base/jboss-eap:6.3
MAINTAINER Jesús Cózar <jesuscozar@guadaltel.es>

ADD standalone.xml /jboss-eap-6.3/standalone/configuration/standalone.xml

EXPOSE 8080 9999
CMD ["/root/run.sh"]